import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: "#FFFFFF",
    padding: 40,
    fontFamily: "Helvetica",
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#111",
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#111",
  },
  subtitle: {
    fontSize: 12,
    color: "#666",
    marginTop: 4,
  },
  section: {
    marginTop: 10,
    marginBottom: 10,
    padding: 10,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#EEE",
    paddingBottom: 4,
  },
  label: {
    fontSize: 12,
    color: "#333",
  },
  value: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#111",
  },
  totalSection: {
    marginTop: 30,
    backgroundColor: "#F8F9FA",
    padding: 20,
    borderRadius: 4,
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#111",
  },
  totalValue: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#2563EB",
  },
});

export interface EstimatePDFProps {
  flatArea: number;
  pitch: string;
  wasteFactor: number;
  pitchAdjustedArea: number;
  wasteArea: number;
  finalArea: number;
  squares: number;
}

export const EstimatePDF = ({
  flatArea,
  pitch,
  wasteFactor,
  pitchAdjustedArea,
  wasteArea,
  finalArea,
  squares,
}: EstimatePDFProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>RoofMetrics Estimate</Text>
        <Text style={styles.subtitle}>
          Professional Roofing Measurement Report
        </Text>
      </View>

      <View style={styles.section}>
        <View style={styles.row}>
          <Text style={styles.label}>Flat Drawn Area:</Text>
          <Text style={styles.value}>{flatArea.toFixed(2)} sq ft</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Roof Pitch:</Text>
          <Text style={styles.value}>{pitch}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Pitch Adjusted Area:</Text>
          <Text style={styles.value}>{pitchAdjustedArea.toFixed(2)} sq ft</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Waste Factor ({wasteFactor}%):</Text>
          <Text style={styles.value}>{wasteArea.toFixed(2)} sq ft</Text>
        </View>
      </View>

      <View style={styles.totalSection}>
        <View style={styles.row}>
          <Text style={styles.totalLabel}>Total Estimated Area:</Text>
          <Text style={styles.value}>{finalArea.toFixed(2)} sq ft</Text>
        </View>
        <View style={styles.totalRow}>
          <Text style={styles.totalLabel}>Materials Needed (Squares):</Text>
          <Text style={styles.totalValue}>{squares} SQ</Text>
        </View>
      </View>

      <View style={{ marginTop: 40 }}>
        <Text style={{ fontSize: 10, color: "#999", textAlign: "center" }}>
          This estimate is generated by RoofMetrics SaaS. It is intended for
          estimation purposes only. Final material orders should be verified by
          a professional on site.
        </Text>
      </View>
    </Page>
  </Document>
);
